### PR TITLE
Update fr-FR.php

### PR DESCRIPTION
**Pull request by IEDfactory**
Hi again Vince,

Here is the version 2 of the translation of Jomres, following test on site. I found some syntax errors I had made. I just tested it, it does not return syntax error in the back-end ...

I will now be able to activate the fr-FR.php to re-read all the translations in their context

I was also looking for the files in the following folders that I will translate as soon as possible ...

/administrator/components/com_jomres/language/en-GB
/administrator/language/en-GB
/modules/mod_itpsocialbuttons/language/en-GB
/modules/mod_vina_camera_image_slider/languages
/templates/jr_leotian/language/en-GB

To be continued

Best regards

### CODE REVIEW

**Comment by ValtariNumAgency** [comment]
If you agree, I prefer to communicate by mail?

**Comment by IEDfactory** [comment]
[:jomres:languageV3.zip](https://github.com/WoollyinWalesIT/jomres/files/3301184/jomres.languageV3.zip)
Hi Vince,
In attachment Version 3 to insert in nightly version

**Comment by IEDfactory** [comment]
Hi Vince,
In attachment Version 4
[:jomres:languageV4.zip](https://github.com/WoollyinWalesIT/jomres/files/3306814/jomres.languageV4.zip)
 to insert in nightly version

Best regards and great thanks for your reactivity

**Comment by ValtariNumAgency** [comment]
Hi Vince
In attachment Version 5 to Nightly version.
I'v installed all translation in a stable version and they're works...
Best regards
[:jomres:languageV5.zip](https://github.com/WoollyinWalesIT/jomres/files/3360041/jomres.languageV5.zip)

**Pull request merged**
